import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { auth } from '@/auth';
import { SessionProvider } from 'next-auth/react';
import { Toaster } from 'sonner';
import { GlobalState } from '@/global/global-state';
import { ModalProvider } from '@/global/modal-provider';
import AuthErrorBoundary from '@/components/error-boundary/auth-error-boundary';
import { ThemeProvider } from '@/components/providers/theme-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <AuthErrorBoundary>
      <SessionProvider session={session}>
        <html lang="en" suppressHydrationWarning>
          <body>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <GlobalState>
                <ModalProvider />

                {children}
              </GlobalState>
              <Toaster closeButton />
            </ThemeProvider>
          </body>
        </html>
      </SessionProvider>
    </AuthErrorBoundary>
  );
}
